use pap22Z_z03;

DROP TABLE IF EXISTS Settings;
CREATE TABLE Settings (
    ProfileID INT UNIQUE NOT NULL AUTO_INCREMENT,
    Name VARCHAR(40) UNIQUE NOT NULL,
    MusicVolume INT NOT NULL,
    SFXVolume INT NOT NULL,
    GameSpeed DECIMAL(3, 2) NOT NULL,
    GameLength INTEGER NOT NULL
);
INSERT INTO Settings VALUES(NULL, 'default', 50, 50, 1.0, 20);
